// Autogenerated from Pigeon (v17.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "messages.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface FLTBook ()
+ (FLTBook *)fromList:(NSArray *)list;
+ (nullable FLTBook *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation FLTBook
+ (instancetype)makeWithTitle:(nullable NSString *)title
    urlImage:(nullable NSString *)urlImage {
  FLTBook* pigeonResult = [[FLTBook alloc] init];
  pigeonResult.title = title;
  pigeonResult.urlImage = urlImage;
  return pigeonResult;
}
+ (FLTBook *)fromList:(NSArray *)list {
  FLTBook *pigeonResult = [[FLTBook alloc] init];
  pigeonResult.title = GetNullableObjectAtIndex(list, 0);
  pigeonResult.urlImage = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable FLTBook *)nullableFromList:(NSArray *)list {
  return (list) ? [FLTBook fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    self.title ?: [NSNull null],
    self.urlImage ?: [NSNull null],
  ];
}
@end

@interface FLTBookApiCodecReader : FlutterStandardReader
@end
@implementation FLTBookApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [FLTBook fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FLTBookApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTBookApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[FLTBook class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FLTBookApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTBookApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTBookApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTBookApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTBookApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FLTBookApiCodecReaderWriter *readerWriter = [[FLTBookApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpFLTBookApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTBookApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.pigeon_demo.BookApi.search"
        binaryMessenger:binaryMessenger
        codec:FLTBookApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(searchKeyword:error:)], @"FLTBookApi api (%@) doesn't respond to @selector(searchKeyword:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_keyword = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSArray<FLTBook *> *output = [api searchKeyword:arg_keyword error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
