// Autogenerated from Pigeon (v17.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTMessageApi.
NSObject<FlutterMessageCodec> *FLTMessageApiGetCodec(void);

@protocol FLTMessageApi
- (void)sendMessageMessage:(NSString *)message error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFLTMessageApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTMessageApi> *_Nullable api);

NS_ASSUME_NONNULL_END
